version: '3.1'

services:

  db:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=qwerty